## Hypothesis Testing Assignment

In [21]:
#Importing necessary packages
import pandas as pd
import numpy as np
# package with hypothesis tests
import scipy.stats as st

### Data

You can download the data from [**here**](https://drive.google.com/file/d/0Bz9_0VdXvv9bUUNlUTVrMF9VcVU/view?usp=sharing&resourcekey=0-16O9Fc5eaJH99-M7AHqHOg). The data contains results of all NBA games from seasons 2013/2014 to 2015/2016.

In [22]:
df = pd.read_csv(r'nba_games_2013_2015.csv', delimiter=';')

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7380 entries, 0 to 7379
Data columns (total 28 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   SEASON_ID          7380 non-null   int64
 1   TEAM_ID            7380 non-null   int64
 2   TEAM_ABBREVIATION  7380 non-null   object
 3   TEAM_NAME          7380 non-null   object
 4   GAME_ID            7380 non-null   int64
 5   GAME_DATE          7380 non-null   object
 6   MATCHUP            7380 non-null   object
 7   WL                 7380 non-null   object
 8   MIN                7380 non-null   int64
 9   PTS                7380 non-null   int64
 10  FGM                7380 non-null   int64
 11  FGA                7380 non-null   int64
 12  FG_PCT             7380 non-null   float64
 13  FG3M               7380 non-null   int64
 14  FG3A               7380 non-null   int64
 15  FG3_PCT            7380 non-null   float64
 16  FTM                7380 non-null   int64
 17  FTA                7380 non-null   int64
 18  FT_PCT             7380 non-null   float64
 19  OREB               7380 non-null   int64
 20  DREB               7380 non-null   int64
 21  REB                7380 non-null   int64
 22  AST                7380 non-null   int64
 23  STL                7380 non-null   int64
 24  BLK                7380 non-null   int64
 25  TOV                7380 non-null   int64
 26  PF                 7380 non-null   int64
 27  PLUS_MINUS         7380 non-null   float64
dtypes: float64(4), int64(19), object(5)
memory usage: 1.6+ MB

--------------
### Task 1
Split the data into **3** separate dataframes for each NBA season!

In [24]:
df['SEASON_ID'].unique()

array([22015, 22014, 22013])

In [25]:
df22015 = df[df['SEASON_ID'] == 22015]
df22014 = df[df['SEASON_ID'] == 22014]
df22013 = df[df['SEASON_ID'] == 22013]

In [26]:
df22013['SEASON_ID'].unique()

array([22013])

---------------
### Task 2
Test the hypothesis that the offensive productions stats of the Cleveland Cavaliers and Golden State Warriors (the teams that met in the finals that year) were from the same distribution in the 2015/2016 season.

Offensive production refers to two variables: **PTS (Points)** and **FG_PCT (Field Goal Percentage)**. We will need to do two separate hypothesis tests, one for each variable.

In [27]:
## team names

df22015['TEAM_NAME'].unique()

array(['Minnesota Timberwolves', 'Milwaukee Bucks', 'Boston Celtics',
       'Los Angeles Lakers', 'Cleveland Cavaliers', 'Sacramento Kings',
       'LA Clippers', 'Washington Wizards', 'Atlanta Hawks',
       'Toronto Raptors', 'New Orleans Pelicans', 'Orlando Magic',
       'Utah Jazz', 'Golden State Warriors', 'Chicago Bulls',
       'Miami Heat', 'Memphis Grizzlies', 'San Antonio Spurs',
       'Charlotte Hornets', 'Brooklyn Nets', 'Dallas Mavericks',
       'Houston Rockets', 'Philadelphia 76ers', 'Portland Trail Blazers',
       'Phoenix Suns', 'Denver Nuggets', 'Indiana Pacers',
       'Detroit Pistons', 'New York Knicks', 'Oklahoma City Thunder'],
      dtype=object)

In [29]:
## Specify the two teams to look at
df22015_cleveland = df22015[df22015['TEAM_NAME'] == "Cleveland Cavaliers"]
df22015_golden = df22015[df22015['TEAM_NAME'] == "Golden State Warriors"]

df22015_cleveland

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
4,22015,1610612739,CLE,Cleveland Cavaliers,21501220,2016-04-13,CLE vs. DET,L,265,110,...,0.733,8,35,43,21,4,7,10,23,-2.0
40,22015,1610612739,CLE,Cleveland Cavaliers,21501203,2016-04-11,CLE vs. ATL,W,240,109,...,0.900,9,38,47,17,9,4,15,14,15.0
78,22015,1610612739,CLE,Cleveland Cavaliers,21501191,2016-04-09,CLE @ CHI,L,242,102,...,0.611,12,30,42,24,5,5,15,18,-3.0
127,22015,1610612739,CLE,Cleveland Cavaliers,21501165,2016-04-06,CLE @ IND,L,239,109,...,0.912,7,26,33,15,7,3,10,19,-14.0
151,22015,1610612739,CLE,Cleveland Cavaliers,21501159,2016-04-05,CLE @ MIL,W,241,109,...,0.900,2,39,41,30,4,8,16,14,29.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2336,22015,1610612739,CLE,Cleveland Cavaliers,21500063,2015-11-04,CLE vs. NYK,W,239,96,...,0.719,9,39,48,21,5,2,11,12,10.0
2364,22015,1610612739,CLE,Cleveland Cavaliers,21500046,2015-11-02,CLE @ PHI,W,240,107,...,0.750,7,36,43,28,5,9,16,19,7.0
2399,22015,1610612739,CLE,Cleveland Cavaliers,21500021,2015-10-30,CLE vs. MIA,W,238,102,...,0.857,14,35,49,25,4,4,11,19,10.0
2440,22015,1610612739,CLE,Cleveland Cavaliers,21500011,2015-10-28,CLE @ MEM,W,240,106,...,0.647,12,42,54,29,7,2,19,25,30.0
2456,22015,1610612739,CLE,Cleveland Cavaliers,21500002,2015-10-27,CLE @ CHI,L,240,95,...,0.588,11,39,50,26,5,7,10,21,-2.0

In [139]:
## test points
from scipy.stats import mannwhitneyu

points_stat, points_p = mannwhitneyu(df22015_cleveland["PTS"], df22015_golden["PTS"])

if points_p > 0.05:
    print('Probably same')
else:
    print('Probably not')
    
print(type(points_p))
print(type(0.05))
print(points_p)

Probably not
<class 'numpy.float64'>
<class 'float'>
3.3671757008234084e-08

In [140]:
goals_stat, goals_p = mannwhitneyu(df22015_cleveland["FG_PCT"], df22015_golden["FG_PCT"])

if goals_p > 0.05:
    print('Probably same')
else:
    print('Probably not')
    
print(goals_p)

Probably not
0.0027906556653745263

0.0027906556653745263

-----------------
### Task 3
Test the hypothesis that the number of points (PTS) scored by Cleveland Cavaliers changed significantly after the head coach changed in the 2015/2016 season.

- **Coach Blatt was fired on 24th of Jan, 2016**. 

Use the data from seasons 2014/2015 and 2015/2016 - those are years when Cleveland was coached by Blatt. 

**We have two possible solutions to try here:**
- Take the same amount of games from before and after and try t-test.
- Take all the games from before and after and look for the right test to compare two samples with different sizes. (You will need to go through the scipy documentation or google to figure out what kind of test is required.)

In [124]:
## Use T Test

df_before = df[df["GAME_DATE"] < "2016-01-24"]
df_after = df[df["GAME_DATE"] > "2016-01-24"]

coach_stats, coach_p = st.ttest_ind(df_before["PTS"], df_after["PTS"], equal_var=False)

alpha = 0.05
if coach_p < alpha:
    print('The change was significant')
else:
    print('No significant change')

print(coach_p)
print(df_before["PTS"].mean())
print(df_after["PTS"].mean())

The change was significant
1.4492262613944057e-21
100.66757449535406
104.31061946902655

----------------


### Task 4
Download [**the similar dataset**](https://drive.google.com/file/d/0Bz9_0VdXvv9bRHhuRTI1aXBQcTA/view?usp=sharing&resourcekey=0-jGIaWyk0bXyECNSzB3x38w) with scores from playoff games in 2016.

In [128]:
df_playoffs = pd.read_csv(r'nba_playoff_games_2016.csv', delimiter=';')
df_playoffs

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,42015,1610612739,CLE,Cleveland Cavaliers,41500407,2016-06-19,CLE @ GSW,W,241,93,...,0.840,9,39,48,17,7,6,11,15,4.0
1,42015,1610612744,GSW,Golden State Warriors,41500407,2016-06-19,GSW vs. CLE,L,239,89,...,0.769,7,32,39,22,7,5,10,23,-4.0
2,42015,1610612744,GSW,Golden State Warriors,41500406,2016-06-16,GSW @ CLE,L,238,101,...,0.690,9,26,35,19,5,3,14,25,-14.0
3,42015,1610612739,CLE,Cleveland Cavaliers,41500406,2016-06-16,CLE vs. GSW,W,240,115,...,0.781,8,37,45,24,12,7,10,25,14.0
4,42015,1610612739,CLE,Cleveland Cavaliers,41500405,2016-06-13,CLE @ GSW,W,241,112,...,0.609,8,33,41,15,11,9,16,22,15.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167,42015,1610612760,OKC,Oklahoma City Thunder,41500161,2016-04-16,OKC vs. DAL,W,243,108,...,0.857,14,42,56,23,7,6,18,25,38.0
168,42015,1610612737,ATL,Atlanta Hawks,41500131,2016-04-16,ATL vs. BOS,W,238,102,...,0.771,13,40,53,23,4,9,11,20,1.0
169,42015,1610612745,HOU,Houston Rockets,41500141,2016-04-16,HOU @ GSW,L,240,78,...,0.500,13,38,51,16,10,6,24,28,-26.0
170,42015,1610612742,DAL,Dallas Mavericks,41500161,2016-04-16,DAL @ OKC,L,238,70,...,0.615,9,24,33,16,5,0,12,25,-38.0
171,42015,1610612738,BOS,Boston Celtics,41500131,2016-04-16,BOS @ ATL,L,239,101,...,0.842,15,35,50,27,6,6,10,32,-1.0

------------
### Task 5
Test the hypothesis that **number of blocks (BLK)** are from the same distribution in both the NBA playoffs and in the NBA regular season for 2015/2016 seaon for the **Toronto Raptors**. 

- We will be working with two samples with different sizes again.

In [136]:
## Pull relevant raptors info
df_regular_raptors = df22015[df22015["TEAM_NAME"] == "Toronto Raptors"]
df_playoffs_raptors = df_playoffs[df_playoffs["TEAM_NAME"] == "Toronto Raptors"]
df_playoffs_raptors

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
19,42015,1610612761,TOR,Toronto Raptors,41500306,2016-05-27,TOR vs. CLE,L,240,87,...,0.765,7,26,33,10,6,2,12,19,-26.0
22,42015,1610612761,TOR,Toronto Raptors,41500305,2016-05-25,TOR @ CLE,L,239,78,...,0.600,5,22,27,19,9,3,18,25,-38.0
26,42015,1610612761,TOR,Toronto Raptors,41500304,2016-05-23,TOR vs. CLE,W,239,105,...,0.737,9,26,35,17,8,3,8,16,6.0
31,42015,1610612761,TOR,Toronto Raptors,41500303,2016-05-21,TOR vs. CLE,W,241,99,...,0.846,12,42,54,15,1,4,9,17,15.0
32,42015,1610612761,TOR,Toronto Raptors,41500302,2016-05-19,TOR @ CLE,L,239,89,...,0.778,7,31,38,17,6,4,12,31,-19.0
36,42015,1610612761,TOR,Toronto Raptors,41500301,2016-05-17,TOR @ CLE,L,242,84,...,0.750,4,19,23,19,8,1,14,25,-31.0
40,42015,1610612761,TOR,Toronto Raptors,41500217,2016-05-15,TOR vs. MIA,W,241,116,...,0.674,20,30,50,17,8,4,9,23,27.0
43,42015,1610612761,TOR,Toronto Raptors,41500216,2016-05-13,TOR @ MIA,L,240,91,...,0.760,8,35,43,10,4,4,8,18,-12.0
46,42015,1610612761,TOR,Toronto Raptors,41500215,2016-05-11,TOR vs. MIA,W,239,99,...,0.846,11,28,39,16,10,7,9,20,8.0
55,42015,1610612761,TOR,Toronto Raptors,41500214,2016-05-09,TOR @ MIA,L,266,87,...,0.789,7,32,39,12,7,2,14,23,-7.0
61,42015,1610612761,TOR,Toronto Raptors,41500213,2016-05-07,TOR @ MIA,W,240,95,...,0.750,6,29,35,16,5,0,13,22,4.0
69,42015,1610612761,TOR,Toronto Raptors,41500212,2016-05-05,TOR vs. MIA,W,266,96,...,0.538,13,26,39,14,15,1,9,21,4.0
72,42015,1610612761,TOR,Toronto Raptors,41500211,2016-05-03,TOR vs. MIA,L,265,96,...,0.733,4,37,41,19,10,6,15,25,-6.0
84,42015,1610612761,TOR,Toronto Raptors,41500117,2016-05-01,TOR vs. IND,W,240,89,...,0.765,18,31,49,21,7,7,8,12,5.0
91,42015,1610612761,TOR,Toronto Raptors,41500116,2016-04-29,TOR @ IND,L,241,83,...,0.640,15,25,40,14,9,5,16,23,-18.0
102,42015,1610612761,TOR,Toronto Raptors,41500115,2016-04-26,TOR vs. IND,W,241,102,...,0.857,12,29,41,12,9,3,7,18,3.0
123,42015,1610612761,TOR,Toronto Raptors,41500114,2016-04-23,TOR @ IND,L,239,83,...,0.700,11,29,40,12,8,3,17,20,-17.0
135,42015,1610612761,TOR,Toronto Raptors,41500113,2016-04-21,TOR @ IND,W,239,101,...,0.813,15,30,45,18,6,4,11,27,16.0
152,42015,1610612761,TOR,Toronto Raptors,41500112,2016-04-18,TOR vs. IND,W,240,98,...,0.920,12,32,44,19,8,5,13,25,11.0
166,42015,1610612761,TOR,Toronto Raptors,41500111,2016-04-16,TOR vs. IND,L,240,90,...,0.684,20,32,52,17,6,5,19,27,-10.0

In [137]:
## perform Welch's test
raptors_stats, raptors_p = st.ttest_ind(df_regular_raptors["BLK"], df_playoffs_raptors["BLK"], equal_var=False)
print(raptors_p)
if raptors_p < alpha:
    print('The change was significant')
else:
    print('No significant change')

0.0011403514552816168
The change was significant


-----------------
### Task 6
Test the hypothesis that the number of points (PTS) scored by Cleveland Cavaliers is equally distributed for all 3 seasons. 

- In this case, we need a hypothesis test that compares more than 2 distributions at the same. (You will need to go through the scipy documentation or google to figure out what kind of test is required.)

In [142]:
## Pull data from all three seasons

df22015_cleveland = df22015[df22015['TEAM_NAME'] == "Cleveland Cavaliers"]
df22014_cleveland = df22014[df22014['TEAM_NAME'] == "Cleveland Cavaliers"]
df22013_cleveland = df22013[df22013['TEAM_NAME'] == "Cleveland Cavaliers"]

df22013_cleveland

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
4947,22013,1610612739,CLE,Cleveland Cavaliers,21301224,2014-04-16,CLE vs. BKN,W,239,114,...,0.824,13,38,51,32,10,7,12,18,29.0
4992,22013,1610612739,CLE,Cleveland Cavaliers,21301193,2014-04-12,CLE vs. BOS,L,239,99,...,0.667,15,34,49,22,2,2,11,20,-12.0
5013,22013,1610612739,CLE,Cleveland Cavaliers,21301185,2014-04-11,CLE @ MIL,L,240,116,...,0.800,11,29,40,18,11,4,10,27,-3.0
5054,22013,1610612739,CLE,Cleveland Cavaliers,21301162,2014-04-09,CLE vs. DET,W,240,122,...,0.556,13,34,47,41,8,6,15,24,22.0
5088,22013,1610612739,CLE,Cleveland Cavaliers,21301145,2014-04-05,CLE vs. CHA,L,266,94,...,0.810,10,41,51,22,5,3,11,18,-2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7248,22013,1610612739,CLE,Cleveland Cavaliers,21300066,2013-11-06,CLE @ MIL,L,240,104,...,0.727,12,27,39,20,10,2,9,21,-5.0
7282,22013,1610612739,CLE,Cleveland Cavaliers,21300047,2013-11-04,CLE vs. MIN,W,240,93,...,0.909,11,38,49,22,10,12,23,24,1.0
7303,22013,1610612739,CLE,Cleveland Cavaliers,21300033,2013-11-02,CLE @ IND,L,240,74,...,0.867,6,31,37,11,15,1,16,25,-15.0
7316,22013,1610612739,CLE,Cleveland Cavaliers,21300020,2013-11-01,CLE @ CHA,L,241,84,...,0.727,11,31,42,14,9,1,17,29,-6.0
7355,22013,1610612739,CLE,Cleveland Cavaliers,21300004,2013-10-30,CLE vs. BKN,W,241,98,...,0.676,16,32,48,21,7,3,11,20,4.0

In [143]:
cleveland_test, cleveland_p = st.f_oneway(
    df22015_cleveland["PTS"],
    df22014_cleveland["PTS"],
    df22013_cleveland["PTS"]
)

if cleveland_p < alpha:
    print('The change was significant')
else:
    print('No significant change')

The change was significant

#### Follow Up
**Between which seasons can we see the significant difference?**

+ Unfortunatelly, this is not the output of an ANOVA test and further tests are needed to be run.
+ Note: Lebron James came back to the Cleveland Caveliers prior to season 2014/2015. We can use this fact to interpret our results correctly.